# CMAKE generated file: DO NOT EDIT!
<<<<<<< HEAD
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

=======
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

<<<<<<< HEAD

# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


=======
# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
<<<<<<< HEAD
CMAKE_SOURCE_DIR = /home/pi/Desktop/pmm_pipelining_cpp/pmm_pipelining_min/PhaseBasedMotionMagification

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/pmm_pipelining_cpp/pmm_pipelining_min/PhaseBasedMotionMagification
=======
CMAKE_SOURCE_DIR = /home/imbedded/Desktop/trigger_pbm/pmm_pipelining_min/PhaseBasedMotionMagification

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/imbedded/Desktop/trigger_pbm/pmm_pipelining_min/PhaseBasedMotionMagification
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5

#=============================================================================
# Targets provided globally by CMake.

<<<<<<< HEAD
# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
<<<<<<< HEAD

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/pmm_pipelining_cpp/pmm_pipelining_min/PhaseBasedMotionMagification/CMakeFiles /home/pi/Desktop/pmm_pipelining_cpp/pmm_pipelining_min/PhaseBasedMotionMagification//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/pmm_pipelining_cpp/pmm_pipelining_min/PhaseBasedMotionMagification/CMakeFiles 0
=======
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imbedded/Desktop/trigger_pbm/pmm_pipelining_min/PhaseBasedMotionMagification/CMakeFiles /home/imbedded/Desktop/trigger_pbm/pmm_pipelining_min/PhaseBasedMotionMagification//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imbedded/Desktop/trigger_pbm/pmm_pipelining_min/PhaseBasedMotionMagification/CMakeFiles 0
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhaseBasedMotionMagnification

# Build rule for target.
PhaseBasedMotionMagnification: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhaseBasedMotionMagnification
.PHONY : PhaseBasedMotionMagnification

# fast build rule for target.
PhaseBasedMotionMagnification/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/build
.PHONY : PhaseBasedMotionMagnification/fast

calculate_process.o: calculate_process.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : calculate_process.o

# target to build an object file
calculate_process.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/calculate_process.cc.o
.PHONY : calculate_process.cc.o

calculate_process.i: calculate_process.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : calculate_process.i

# target to preprocess a source file
calculate_process.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/calculate_process.cc.i
.PHONY : calculate_process.cc.i

calculate_process.s: calculate_process.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : calculate_process.s

# target to generate assembly for a file
calculate_process.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/calculate_process.cc.s
.PHONY : calculate_process.cc.s

complex_steerable_pyramid.o: complex_steerable_pyramid.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : complex_steerable_pyramid.o

# target to build an object file
complex_steerable_pyramid.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/complex_steerable_pyramid.cc.o
.PHONY : complex_steerable_pyramid.cc.o

complex_steerable_pyramid.i: complex_steerable_pyramid.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : complex_steerable_pyramid.i

# target to preprocess a source file
complex_steerable_pyramid.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/complex_steerable_pyramid.cc.i
.PHONY : complex_steerable_pyramid.cc.i

complex_steerable_pyramid.s: complex_steerable_pyramid.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : complex_steerable_pyramid.s

# target to generate assembly for a file
complex_steerable_pyramid.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/complex_steerable_pyramid.cc.s
.PHONY : complex_steerable_pyramid.cc.s

firwin_manager.o: firwin_manager.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : firwin_manager.o

# target to build an object file
firwin_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/firwin_manager.cc.o
.PHONY : firwin_manager.cc.o

firwin_manager.i: firwin_manager.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : firwin_manager.i

# target to preprocess a source file
firwin_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/firwin_manager.cc.i
.PHONY : firwin_manager.cc.i

firwin_manager.s: firwin_manager.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : firwin_manager.s

# target to generate assembly for a file
firwin_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/firwin_manager.cc.s
.PHONY : firwin_manager.cc.s

logging_manager.o: logging_manager.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : logging_manager.o

# target to build an object file
logging_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/logging_manager.cc.o
.PHONY : logging_manager.cc.o

logging_manager.i: logging_manager.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : logging_manager.i

# target to preprocess a source file
logging_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/logging_manager.cc.i
.PHONY : logging_manager.cc.i

logging_manager.s: logging_manager.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : logging_manager.s

# target to generate assembly for a file
logging_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/logging_manager.cc.s
.PHONY : logging_manager.cc.s

main.o: main.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/main.cc.s
.PHONY : main.cc.s

storage_manager.o: storage_manager.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : storage_manager.o

# target to build an object file
storage_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/storage_manager.cc.o
.PHONY : storage_manager.cc.o

storage_manager.i: storage_manager.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : storage_manager.i

# target to preprocess a source file
storage_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/storage_manager.cc.i
.PHONY : storage_manager.cc.i

storage_manager.s: storage_manager.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : storage_manager.s

# target to generate assembly for a file
storage_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/storage_manager.cc.s
.PHONY : storage_manager.cc.s

streaming_manager.o: streaming_manager.cc.o
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : streaming_manager.o

# target to build an object file
streaming_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/streaming_manager.cc.o
.PHONY : streaming_manager.cc.o

streaming_manager.i: streaming_manager.cc.i
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : streaming_manager.i

# target to preprocess a source file
streaming_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/streaming_manager.cc.i
.PHONY : streaming_manager.cc.i

streaming_manager.s: streaming_manager.cc.s
<<<<<<< HEAD

=======
>>>>>>> 853558df90076385a81b1325c4a40e7d57e464c5
.PHONY : streaming_manager.s

# target to generate assembly for a file
streaming_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhaseBasedMotionMagnification.dir/build.make CMakeFiles/PhaseBasedMotionMagnification.dir/streaming_manager.cc.s
.PHONY : streaming_manager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PhaseBasedMotionMagnification"
	@echo "... calculate_process.o"
	@echo "... calculate_process.i"
	@echo "... calculate_process.s"
	@echo "... complex_steerable_pyramid.o"
	@echo "... complex_steerable_pyramid.i"
	@echo "... complex_steerable_pyramid.s"
	@echo "... firwin_manager.o"
	@echo "... firwin_manager.i"
	@echo "... firwin_manager.s"
	@echo "... logging_manager.o"
	@echo "... logging_manager.i"
	@echo "... logging_manager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... storage_manager.o"
	@echo "... storage_manager.i"
	@echo "... storage_manager.s"
	@echo "... streaming_manager.o"
	@echo "... streaming_manager.i"
	@echo "... streaming_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

